### ISSUE TITLE
Company.marketCap casting int to string field

### ISSUE THREAD

**Issue by philipithomas** [clearbit/clearbit-go#18]
I'm getting this error in production:

<img width="649" alt="screen shot 2017-12-12 at 11 07 14 am" src="https://user-images.githubusercontent.com/1312414/33903317-df45875e-df2c-11e7-83bf-c183c120454e.png">

Simple fix would be converting the `marketCap` string field to an int. However, I'm concerned that the API isn't returning a consistent type. 

@davidlumley @mattatcha - can you confirm the API return type? Until this is fixed, enrichment is erroring in our app while chewing through our quota . . .

**Comment by philipithomas** [comment]
Here's the line https://github.com/clearbit/clearbit-go/blob/master/clearbit/company.go#L86

**Comment by davidlumley** [comment]
Looks like it was accidentally changed from an `int` to a `string` here: https://github.com/clearbit/clearbit-go/commit/ce4492d81bdb72e8f7a6e7cda321226a8eb93538

Would you mind submitting a PR to change it back? 🙏
