### ISSUE TITLE
Enrichment API support

### ISSUE THREAD

**Issue by baldrich-randori** [clearbit/clearbit-go#30]
I was looking to leverage the enrichment API but it looks like you don't support it through the golang API?

**Comment by harlow** [comment]
hi @baldrich-randori the Enrichment APIs are supported. They are under `Person` and `Company` and use can use an Email or Domain as inputs:

https://github.com/clearbit/clearbit-go/blob/master/clearbit/examples_test.go#L156-L169

**Comment by baldrich-randori** [comment]
Thanks for your help, I went this direction as well but it seems like we have to do each query separate for the domain and the email where the python api supports this https://clearbit.com/docs#enrichment-api.
