### ISSUE TITLE
Enrichment failing

### ISSUE THREAD

**Issue by philipithomas** [clearbit/clearbit-go#9]
Getting this error in production:

> json: cannot unmarshal number into Go struct field .id of type string,

It's stopping this library from completing enrichment.

**Comment by philipithomas** [comment]
Github ID appears to be an integer from your API, but it is a string in the user struct

**Comment by philipithomas** [comment]
Oddly, the user twitter ID is an integer, and the company twitter ID is a string. That doesn't make sense @maccman  :-P

**Comment by harlow** [comment]
@philipithomas nice catch. Agree those should def be consistent. 

> The integer representation of the unique identifier for this Tweet. This number is greater than 53 bits and some programming languages may have difficulty/silent defects in interpreting it. Using a signed 64 bit integer for storing this identifier is safe. Use id_str for fetching the identifier to stay on the safe side. See Twitter IDs, JSON and Snowflake .

**Comment by maccman** [comment]
Oops - should def be using strings for both.

**Comment by philipithomas** [comment]
For the future, the is the best way I've seen for turning JSON into Go structs:

https://mholt.github.io/json-to-go/

**Comment by philipithomas** [comment]
Might be good to set up some basic integration testing on this library because Go is tricky with JSON integrations. Basically, have it query API and assert no error. It would be best to run this daily or so (which TravisCI could do)

**Comment by philipithomas** [comment]
`following` and `followers` for Twitter also incorrect type - fix incoming

**Comment by philipithomas** [comment]
Does `Company` no longer return a URL?
